# Generated by Django 5.0.3 on 2024-03-15 23:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('eng_name', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wilayas_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': 'Wilayas',
            },
        ),
        migrations.CreateModel(
            name='Municipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('eng_name', models.CharField(max_length=20)),
                ('population', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipals_created', to=settings.AUTH_USER_MODEL)),
                ('wilaya_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipals', to='municipal_wilaya.wilaya')),
            ],
            options={
                'verbose_name': 'Municipal',
                'verbose_name_plural': 'Municipals',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('eng_name', models.CharField(max_length=150)),
                ('wilaya_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipal_wilaya.wilaya')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
    ]
