# Generated by Django 5.0.3 on 2024-03-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_wilaya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wilaya',
            name='user',
        ),
    ]
