# Generated by Django 5.0.3 on 2024-03-15 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_wilaya', '0002_remove_municipal_user_remove_wilaya_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipal',
            old_name='wilaya_id',
            new_name='wilaya',
        ),
    ]
