# Generated by Django 5.0.3 on 2024-03-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_wilaya', '0003_rename_wilaya_id_municipal_wilaya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='wilaya_id',
            new_name='wilaya',
        ),
    ]
