# Generated by Django 5.0.3 on 2024-03-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_wilaya', '0004_rename_wilaya_id_hospital_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipal',
            name='eng_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='municipal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='eng_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
