# Generated by Django 5.0.3 on 2024-04-25 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_wilaya', '0005_alter_municipal_eng_name_alter_municipal_name_and_more'),
        ('pilgrimage_info', '0004_alter_pilgrimageseasoninfo_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('extra_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pilgrimage_info.pilgrimageseasoninfo')),
                ('wilaya', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='municipal_wilaya.wilaya')),
            ],
        ),
    ]
