# Generated by Django 5.0.3 on 2024-04-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_wilaya', '0006_seats'),
        ('pilgrimage_info', '0004_alter_pilgrimageseasoninfo_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilgrimage_info.pilgrimageseasoninfo'),
        ),
    ]
