# Generated by Django 5.0.4 on 2024-04-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_wilaya', '0007_alter_seats_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipal',
            name='is_lottery_done',
            field=models.BooleanField(default=False),
        ),
    ]
