# Generated by Django 5.0.3 on 2024-03-20 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilgrimage_info', '0004_alter_pilgrimageseasoninfo_year'),
        ('users', '0008_remove_userstatus_end_date_remove_userstatus_phase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantStatusPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilgrimage_info.phase')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userstatus')),
            ],
            options={
                'unique_together': {('participant', 'phase', 'status')},
            },
        ),
    ]
