# Generated by Django 5.0.3 on 2024-03-20 01:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
        ('pilgrimage_info', '0004_alter_pilgrimageseasoninfo_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantstatusphase',
            unique_together={('participant', 'phase')},
        ),
    ]
