# Generated by Django 5.0.3 on 2024-03-21 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_alter_participantstatusphase_unique_together'),
        ('pilgrimage_info', '0004_alter_pilgrimageseasoninfo_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('RND', 'Random'), ('WTD', 'Weighted'), ('PRT', 'Priority'), ('HYB', 'Hybrid')], max_length=3)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pilgrimage_info.pilgrimageseasoninfo')),
            ],
        ),
    ]
