# Generated by Django 5.0.4 on 2024-04-29 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_lotteryalgorithm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantstatusphase',
            name='status',
        ),
    ]
