# Generated by Django 5.0.4 on 2024-05-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_lotteryalgorithm_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryalgorithm',
            name='algorithm',
            field=models.CharField(choices=[('AR', 'Random'), ('A', 'Age'), ('R', 'Registration')], max_length=2),
        ),
    ]
