# Generated by Django 5.0.4 on 2024-05-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaladminprofile',
            name='work_schedule',
            field=models.JSONField(default=list),
        ),
    ]
