# Generated by Django 5.0.3 on 2024-03-26 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0001_initial'),
        ('municipal_wilaya', '0004_rename_wilaya_id_hospital_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaladminprofile',
            name='hospital',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='municipal_wilaya.hospital'),
        ),
    ]
