# Generated by Django 5.0.3 on 2024-03-27 10:38

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0002_medicaladminprofile_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaladminprofile',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='medicaladminprofile',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
