# Generated by Django 5.0.4 on 2024-05-10 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0002_alter_medicaladminprofile_work_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHealthReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('files', models.FileField(blank=True, upload_to='patient_files/')),
                ('medical_opinion', models.TextField()),
                ('is_healthy', models.BooleanField(default=True)),
                ('is_sick', models.BooleanField(default=False)),
                ('diseases', models.ManyToManyField(blank=True, to='accounts_management.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reviews', to=settings.AUTH_USER_MODEL)),
                ('treatments', models.ManyToManyField(blank=True, to='accounts_management.treatment')),
            ],
        ),
    ]
