# Generated by Django 5.0.3 on 2024-03-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0003_medicaladminprofile_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaladminprofile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='medicaladminprofile',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='medicaladminprofile',
            name='state',
        ),
    ]
