# Generated by Django 5.0.4 on 2024-05-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0004_remove_patienthealthreview_diseases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaladminprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='medical_admins/profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='PatientHealthReview',
        ),
    ]
