# Generated by Django 5.0.3 on 2024-03-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0008_alter_medicaladminprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaladminprofile',
            name='hospital',
        ),
    ]
