# Generated by Django 5.0.3 on 2024-03-15 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PilgrimageSeasonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=0)),
                ('ratio', models.FloatField(default=0.0)),
                ('total_pilgrims', models.PositiveIntegerField(default=0)),
                ('inscription_deadline', models.DateField()),
                ('procedure_deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pilgrimage_season_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='pilgrimage_info.pilgrimageseasoninfo')),
            ],
        ),
    ]
