# Generated by Django 5.0.3 on 2024-03-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimage_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='phase_number',
            field=models.PositiveIntegerField(),
        ),
    ]
