# Generated by Django 5.0.3 on 2024-03-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimage_info', '0002_alter_phase_phase_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrimageseasoninfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
