# Generated by Django 5.0.3 on 2024-03-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimage_info', '0003_pilgrimageseasoninfo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrimageseasoninfo',
            name='year',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
