# Generated by Django 5.0.4 on 2024-05-04 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimage_info', '0004_alter_pilgrimageseasoninfo_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilgrimageseasoninfo',
            name='ratio',
        ),
    ]
