# Generated by Django 5.0.4 on 2024-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrimage_info', '0005_remove_pilgrimageseasoninfo_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrimageseasoninfo',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
