# Generated by Django 5.0.3 on 2024-04-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0002_alter_companion_user_alter_personalprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='birth_certificate/'),
        ),
        migrations.AddField(
            model_name='companion',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='identity',
            field=models.FileField(blank=True, null=True, upload_to='identity/'),
        ),
        migrations.AddField(
            model_name='companion',
            name='passport_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='passport_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='birth_certificate/'),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='identity',
            field=models.FileField(blank=True, null=True, upload_to='identity/'),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='passport_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
