# Generated by Django 5.0.3 on 2024-04-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0003_companion_birth_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='birth_certificate',
        ),
        migrations.RemoveField(
            model_name='companion',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='birth_certificate',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='identity',
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
