# Generated by Django 5.0.3 on 2024-03-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('isAdmin', 'admin'), ('isCandidate', 'candidate'), ('isMedicalAdmin', 'medical_admin'), ('isGuide', 'guide')], default='isCandidate', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True),
        ),
    ]
