# Generated by Django 5.0.3 on 2024-03-07 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('Candidate', 'candidate'), ('MedicalAdmin', 'medical_admin'), ('Guide', 'guide')], default='Candidate', max_length=15),
        ),
        migrations.CreateModel(
            name='UserInscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_count', models.IntegerField(default=0)),
                ('latest_inscription_year', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField(choices=[(1, 'won the lottery'), (2, 'accepted in medical visit'), (3, 'successful fees payment'), (4, 'reservation phase')], default=1)),
                ('status', models.CharField(choices=[(' ', 'candidate did not yet finish the phase'), ('P', 'pending (for backup list)'), ('R', 'rejected')], default=' ', max_length=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
