# Generated by Django 5.0.3 on 2024-03-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userinscriptionhistory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('GeneralAdmin', 'general_admin'), ('Candidate', 'candidate'), ('MedicalAdmin', 'medical_admin'), ('Guide', 'guide')], default='Candidate', max_length=15),
        ),
    ]
