# Generated by Django 5.0.3 on 2024-03-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='start_date',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='process',
            field=models.CharField(choices=[('L', 'lottery'), ('V', 'visit'), ('P', 'payment'), ('R', 'reservation')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('R', 'rejected'), ('C', 'confirmed'), ('I', 'in reserve')], default='R', max_length=1),
        ),
    ]
