# Generated by Django 5.0.3 on 2024-03-27 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userstatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinscriptionhistory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
